services:
    doc-chatter-app:
        image: node:18-alpine
        container_name: doc-chatter-app
        volumes:
            - ./../:/app
        working_dir: /app
        ports:
            - 3000:3000
            - 5555:5555
        restart: always
        depends_on:
            - doc-chatter-db
        command: npm run dev

    doc-chatter-db:
        image: postgres:16.0-alpine3.18
        container_name: doc-chatter-db
        restart: always
        environment:
            - PGDATA=/var/lib/postresql/data/pgdata
            - POSTGRES_USER=postgresuser
            - POSTGRES_PASSWORD=postgrespass
        volumes:
            - ./db:/var/lib/postresql/data

    doc-chatter-db-admin:
        image: adminer:4.8.1-standalone
        container_name: doc-chatter-db-admin
        restart: always
        depends_on:
            - doc-chatter-db
        ports:
            - 3001:8080
